name: Deploy Subdomains with Fallback

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare subdomains
        run: |
          mkdir -p out
          
          # Deploy all subdomain-* folders (except subdomain-404)
          for d in subdomain-*; do
            if [ -d "$d" ] && [ "$d" != "subdomain-404" ]; then
              sub="${d#subdomain-}"
              mkdir -p "out/$sub"
              cp -r "$d/"* "out/$sub/"
              echo "$sub.tommustbe12.com" > "out/$sub/CNAME"
            fi
          done
          
          # Add fallback 404 folder for unknown subdomains
          if [ -d "subdomain-404" ]; then
            cp -r subdomain-404 out/_404/
            echo "tommustbe12.com" > out/_404/CNAME
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./out
          force_orphan: true
