name: Deploy Subdomains (separate branches)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy each subdomain folder
        run: |
          for d in subdomain-*; do
            if [ -d "$d" ]; then
              sub="${d#subdomain-}"
              echo "Deploying $d -> branch gh-pages-$sub"

              # Make temp folder
              mkdir -p out
              cp -r "$d"/* out/

              # Add a CNAME for GitHub Pages
              echo "$sub.tommustbe12.com" > out/CNAME

              # Init git inside out
              cd out
              git init
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add .
              git commit -m "Deploy $sub"

              # Push to gh-pages-subdomain branch
              git branch -M gh-pages-$sub
              git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
              git push --force origin gh-pages-$sub
              cd ..
              rm -rf out
            fi
          done
